(async()=>{
  const M=window.MJ_MENU,E=window.MJ_EXTRA||{products:{}};
  if(!M) return;
  const [hero64,prod64]=await Promise.all(['assets/hero-main.webp.b64','assets/product-sprite.webp.b64'].map(u=>fetch(u).then(r=>{if(!r.ok)throw new Error('asset');return r.text()})));
  const A={hero:'data:image/webp;base64,'+hero64.trim(),products:'data:image/webp;base64,'+prod64.trim()};
  document.documentElement.style.setProperty('--sprite',`url("${A.products}")`);
  const C=M.cats,P=M.products,app=document.getElementById('app'),main=document.getElementById('main'),back=document.getElementById('backBtn'),langBtn=document.getElementById('langBtn');
  let lang=localStorage.getItem('mj_lang')||'en';
  const ar=()=>lang==='ar',t=(en,arv)=>ar()?arv:en,esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const catOrder=['arabic','specialty','tea','sparkling'];
  const aliases={'CGLE Tres Dragones':'Methods – CGLE Tres Dragones','Pink Bourbon Punch':'Methods – Pink Bourbon Punch','Bourbon Sidra Sakura':'Methods – Bourbon Sidra Sakura','EA Decaf De Cana':'Methods – EA Decaf De Cana'};
  const slug=s=>s.toLowerCase().replace(/[–—&]/g,'-').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  P.forEach((p,i)=>{p._id=slug(p.nameEn);p._sprite=[i%6,Math.floor(i/6)]});
  function extra(p){return E.products?.[p.nameEn]||E.products?.[aliases[p.nameEn]]||{facts:[]}}
  function facts(p){return extra(p).facts||[]}
  function profile(p){return (ar()?p.profileAr:p.profileEn).split('·').map(x=>x.trim()).filter(Boolean)}
  function caffeineFree(p){return facts(p).some(f=>String(f[1]).trim()==='0 mg')}
  function isEvening(p){return /evening/i.test(p.timeEn)||/المساء/.test(p.timeAr)}
  function setLang(){document.documentElement.lang=lang;document.documentElement.dir=ar()?'rtl':'ltr';app.dir=ar()?'rtl':'ltr';langBtn.textContent=ar()?'EN':'عربي';document.querySelectorAll('[data-nav-label]').forEach(x=>{const k=x.dataset.navLabel,map={home:['Home','الرئيسية'],arabic:['Arabic','عربية'],coffee:['Coffee','قهوة'],tea:['Tea','شاي'],spark:['Sparkling','غازية']};x.textContent=t(...map[k])});render()}
  function route(){let h=location.hash.slice(1)||'/';return h.startsWith('/')?h:'/'+h}
  function navTo(path){if(route()===path)render();else location.hash=path}
  function hero(k,title,desc,count){return `<section class="hero"><img src="${A.hero}" style="object-position:${({arabic:'16% center',specialty:'41% center',tea:'59% center',sparkling:'79% center'})[k]||'50% center'}" alt=""><div class="shade"></div><div class="heroCopy"><div class="eyebrow">${count} ${ar()?'اختيار':'SELECTIONS'}</div><h1>${esc(title)}</h1><p class="lead">${esc(desc)}</p><div class="chips"><span class="chip">${ar()?'مجموعة خاصة':'Private Collection'}</span><span class="chip">AR · EN</span></div></div></section>`}
  function pstyle(p){return `--sx:${p._sprite[0]};--sy:${p._sprite[1]}`}
  function pc(p){return `<button class="productCard" data-go="/product/${p._id}"><div class="thumb" style="${pstyle(p)}"></div><div><div class="pname">${esc(t(p.nameEn,p.nameAr))}</div><div class="profile">${esc(t(p.profileEn,p.profileAr))}</div><div class="micro">${esc(t(p.serveEn,p.serveAr))} · ${esc(t(p.timeEn,p.timeAr))}</div></div><span class="chev">›</span></button>`}
  function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>navTo(b.dataset.go)));document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>navTo('/discover/'+b.dataset.filter)))}
  function home(){const cards=catOrder.map((k,i)=>{let c=C[k],n=P.filter(p=>p.cat===k).length,pos=({arabic:'16% center',specialty:'41% center',tea:'59% center',sparkling:'79% center'})[k];return `<button class="categoryCard" data-go="/collection/${k}"><img src="${A.hero}" style="object-position:${pos}" alt=""><div class="cardCopy"><div class="eyebrow">0${i+1} · ${n} ${ar()?'اختيار':'SELECTIONS'}</div><h3>${esc(t(c.en,c.ar))}</h3><p>${esc(t(c.subEn,c.subAr))}</p></div></button>`}).join('');main.innerHTML=hero('arabic',ar()?'فن الضيافة.':'The art of hosting.',ar()?'أربعة وثلاثون اختيارًا منتقى بعناية، ولكل منتج شخصية وإيحاء وتجربة تقديم خاصة.':'Thirty-four carefully curated selections, each with its own personality, mood and serving experience.',34)+`<section class="section"><div class="eyebrow">${ar()?'اكتشف حسب المزاج':'DISCOVER BY MOOD'}</div><div class="quickRow"><button class="quick" data-filter="signature">${ar()?'التوقيع':'Signature'}</button><button class="quick" data-filter="evening">${ar()?'المساء':'Evening'}</button><button class="quick" data-filter="caffeinefree">${ar()?'دون كافيين':'Caffeine-Free'}</button><button class="quick" data-filter="iced">${ar()?'بارد':'Iced'}</button><button class="quick" data-go="/all">${ar()?'كل الـ34':'All 34'}</button></div><div class="eyebrow" style="margin-top:28px">${ar()?'المجموعة':'THE COLLECTION'}</div><h2 class="title">${ar()?'اختر تجربتك':'Choose your experience'}</h2><p class="desc">${ar()?'ادخل القسم، ثم المجموعة الفرعية، ثم صفحة المنتج الخاصة به.':'Enter a collection, then its sub-collection, then the product’s own editorial page.'}</p><div class="categoryGrid">${cards}</div></section>`;bind()}
  function collection(k){let c=C[k];if(!c)return home();let items=P.filter(p=>p.cat===k),subs=[];for(const p of items)if(!subs.some(s=>s.en===p.subEn))subs.push({en:p.subEn,ar:p.subAr});main.innerHTML=hero(k,t(c.en,c.ar),t(c.subEn,c.subAr),items.length)+`<section class="section"><div class="eyebrow">${ar()?'المجموعات الفرعية':'SUB-COLLECTIONS'}</div><h2 class="title">${ar()?'اختر المسار':'Choose a direction'}</h2><div class="subGrid">${subs.map(s=>{let n=items.filter(p=>p.subEn===s.en).length;return `<button class="subCard" data-go="/collection/${k}/${encodeURIComponent(s.en)}"><div><div class="eyebrow">${n} ${ar()?'اختيارات':'SELECTIONS'}</div><h3>${esc(t(s.en,s.ar))}</h3><p>${esc(t(c.subEn,c.subAr))}</p></div><div class="count">${String(n).padStart(2,'0')}</div></button>`}).join('')}</div><div style="margin-top:26px"><button class="btn" data-go="/collection/${k}/all">${ar()?'عرض كل المنتجات':'View all products'}</button></div></section>`;bind()}
  function subcollection(k,sid){let c=C[k];if(!c)return home();let items=P.filter(p=>p.cat===k),name=decodeURIComponent(sid);if(name!=='all')items=items.filter(p=>p.subEn===name);if(!items.length)return collection(k);let label=name==='all'?t(c.en,c.ar):t(items[0].subEn,items[0].subAr);main.innerHTML=`<section class="section" style="padding-top:34px"><div class="eyebrow">${esc(t(c.en,c.ar))}</div><h1 class="title">${esc(label)}</h1><p class="desc">${esc(t(c.subEn,c.subAr))}</p><div class="productGrid">${items.map(pc).join('')}</div></section>`;bind()}
  function product(id){let p=P.find(x=>x._id===id);if(!p)return all();let c=C[p.cat],fs=facts(p),factsHtml=fs.length?fs.map(f=>`<div class="fact"><div class="factKey">${esc(t(f[0],f[2]))}</div><div class="factVal">${esc(t(f[1],f[3]))}</div></div>`).join(''):`<div class="fact"><div class="factKey">${ar()?'المصدر':'Source'}</div><div class="factVal">${ar()?'بيانات المنتج الموثقة في المجموعة':'Verified collection data'}</div></div>`;let rel=P.filter(x=>x.cat===p.cat&&x._id!==p._id).slice(0,2);main.innerHTML=`<section class="detail"><div class="detailVisual" style="${pstyle(p)}" role="img" aria-label="${esc(t(p.nameEn,p.nameAr))}"></div><div class="detailInfo"><div class="eyebrow">${esc(t(c.en,c.ar))} · ${esc(t(p.subEn,p.subAr))}</div><h1>${esc(t(p.nameEn,p.nameAr))}</h1><div class="tags">${profile(p).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><div class="block"><div class="eyebrow">${ar()?'الشخصية والإيحاء':'CHARACTER & MOOD'}</div><h3>${ar()?'تجربة المنتج':'The product experience'}</h3><p class="story">${esc(t(p.descEn,p.descAr))}</p><div class="experience"><div class="xp"><small>${ar()?'أفضل تقديم':'BEST SERVE'}</small><div>${esc(t(p.serveEn,p.serveAr))}</div></div><div class="xp"><small>${ar()?'أفضل وقت':'BEST TIME'}</small><div>${esc(t(p.timeEn,p.timeAr))}</div></div></div></div><div class="block"><div class="eyebrow">${ar()?'التفاصيل الموثقة':'VERIFIED DETAILS'}</div><div class="facts">${factsHtml}</div></div>${rel.length?`<div class="block"><div class="eyebrow">${ar()?'اكتشف أيضًا':'DISCOVER NEXT'}</div><div class="related">${rel.map(r=>`<button class="relatedBtn" data-go="/product/${r._id}"><b>${esc(t(r.nameEn,r.nameAr))}</b><span>${esc(t(r.subEn,r.subAr))}</span></button>`).join('')}</div></div>`:''}</div></section>`;bind()}
  function filtered(type){let list=P,title='',desc='';if(type==='signature'){list=P.filter(p=>p.nameEn==='Bourbon Sidra Sakura');title=t('House Signature','اختيار البيت');desc=t('The collection’s showpiece.','قطعة العرض الأبرز في المجموعة.')}else if(type==='evening'){list=P.filter(isEvening);title=t('Evening Selection','اختيارات المساء');desc=t('A quieter path through the collection.','مسار أهدأ داخل المجموعة.')}else if(type==='caffeinefree'){list=P.filter(caffeineFree);title=t('Caffeine-Free','دون كافيين');desc=t('Confirmed caffeine-free tea and infusion options.','خيارات الشاي والمنقوعات المؤكد خلوها من الكافيين.')}else if(type==='iced'){list=P.filter(p=>/iced/i.test(p.serveEn)||/بارد/.test(p.serveAr));title=t('Iced Selection','اختيارات باردة');desc=t('Selections that work beautifully cold or over ice.','اختيارات تتألق باردة أو مع الثلج.')}else return all();main.innerHTML=`<section class="section" style="padding-top:34px"><div class="eyebrow">${ar()?'اكتشف حسب المزاج':'DISCOVER BY MOOD'}</div><h1 class="title">${esc(title)}</h1><p class="desc">${esc(desc)}</p><div class="productGrid">${list.map(pc).join('')}</div></section>`;bind()}
  function all(){main.innerHTML=`<section class="searchHero"><div class="eyebrow">${ar()?'المجموعة الكاملة':'FULL COLLECTION'}</div><h1 class="title">${ar()?'كل الـ34 اختيارًا':'All 34 selections'}</h1><label class="searchBox"><span>⌕</span><input id="q" type="search" autocomplete="off" placeholder="${ar()?'ابحث: نعناع، فانيليا، ديكاف…':'Search: mint, vanilla, decaf…'}"></label><div class="quickRow">${catOrder.map(k=>`<button class="quick" data-cat="${k}">${esc(t(C[k].en,C[k].ar))}</button>`).join('')}<button class="quick active" data-cat="all">${ar()?'الكل':'All'}</button></div></section><section class="section" style="padding-top:8px"><div id="results" class="productGrid">${P.map(pc).join('')}</div><p id="empty" class="desc" hidden>${ar()?'لا توجد نتائج.':'No matching selections.'}</p></section>`;bind();let q=document.getElementById('q'),cat='all';function run(){let s=q.value.trim().toLowerCase(),list=P.filter(p=>(cat==='all'||p.cat===cat)&&(!s||[p.nameEn,p.nameAr,p.subEn,p.subAr,p.descEn,p.descAr,p.profileEn,p.profileAr].join(' ').toLowerCase().includes(s)));document.getElementById('results').innerHTML=list.map(pc).join('');document.getElementById('empty').hidden=!!list.length;bind()}q.addEventListener('input',run);document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;document.querySelectorAll('[data-cat]').forEach(x=>x.classList.toggle('active',x===b));run()})}
  function render(){let r=route(),a=r.split('/').filter(Boolean);back.hidden=r==='/';document.querySelectorAll('.bottomNav button').forEach(b=>{const x=b.dataset.active;b.classList.toggle('active',x==='/'?r==='/':!!x&&r.startsWith(x))});if(r==='/')home();else if(a[0]==='collection'&&a[1]&&!a[2])collection(a[1]);else if(a[0]==='collection'&&a[1]&&a[2])subcollection(a[1],a.slice(2).join('/'));else if(a[0]==='product'&&a[1])product(a[1]);else if(a[0]==='discover'&&a[1])filtered(a[1]);else if(a[0]==='all')all();else home();window.scrollTo({top:0,behavior:'auto'})}
  back.addEventListener('click',()=>history.length>1?history.back():navTo('/'));document.getElementById('brandBtn').addEventListener('click',()=>navTo('/'));langBtn.addEventListener('click',()=>{lang=ar()?'en':'ar';localStorage.setItem('mj_lang',lang);setLang()});document.getElementById('searchBtn').addEventListener('click',()=>navTo('/all'));document.querySelectorAll('.bottomNav button').forEach(b=>b.addEventListener('click',()=>navTo(b.dataset.go)));window.addEventListener('hashchange',render);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));setLang();
})();